// Builds the full demo dataset from a locale profile.
//
// The Turkish and English datasets are generated by the same code, so they are
// structurally identical: same number of users, same people suspended, same
// group membership, same job history. That keeps the two screenshot sets
// comparable frame by frame.

import type {
    AdminUser,
    AdminGroup,
    GroupMember,
    GroupAlias,
    GroupSettings,
    OrgUnit,
    Domain,
    StorageUsageData,
} from '../../types/admin';
import type {
    AppConfigDTO,
    ServerJob,
    ServiceAccountStatus,
    OAuthCredentialsStatus,
} from '../../services/server-api';
import type { DemoProfile } from './profiles';
import {
    logoDataUri,
    avatarDataUri,
    signatureWordmarkDataUri,
    socialBadgeDataUri,
    dividerDataUri,
} from '../media';

export const USER_COUNT = 64;

export interface DemoTitle {
    id: number;
    name: string;
    createdBy: string | null;
    updatedBy: string | null;
    createdAt: string;
    updatedAt: string;
}

export interface DemoInstitution extends DemoTitle {
    address: string | null;
    phone: string | null;
}

export interface DemoMedia {
    id: number;
    name: string;
    driveFileId: string;
    publicUrl: string;
    mimeType: string;
    templateId: number;
    createdBy: string | null;
    token: string;
    createdAt: string;
}

export interface DemoTemplate {
    id: number;
    name: string;
    htmlContent: string;
    isDefault: boolean;
    createdBy: string | null;
    updatedBy: string | null;
    createdAt: string;
    updatedAt: string;
}

export interface DemoDataset {
    profile: DemoProfile;
    config: AppConfigDTO;
    authUser: { email: string; name: string; picture: string };
    logoDataUrl: string;
    users: AdminUser[];
    orgUnits: OrgUnit[];
    domains: Domain[];
    groups: AdminGroup[];
    /** group email → members */
    groupMembers: Record<string, GroupMember[]>;
    groupAliases: Record<string, GroupAlias[]>;
    groupSettings: Record<string, GroupSettings>;
    /** user email → group emails */
    userGroups: Record<string, string[]>;
    titles: DemoTitle[];
    institutions: DemoInstitution[];
    templates: DemoTemplate[];
    media: DemoMedia[];
    jobs: ServerJob[];
    loginActivities: any[];
    storage: StorageUsageData;
    serviceAccount: ServiceAccountStatus;
    dwdScopes: string[];
    oauth: OAuthCredentialsStatus;
    /** Signatures already "pushed" to Gmail, keyed by email. */
    signatures: Record<string, string>;
}

const TR_MAP: Record<string, string> = {
    ç: 'c', Ç: 'c', ğ: 'g', Ğ: 'g', ı: 'i', İ: 'i',
    ö: 'o', Ö: 'o', ş: 's', Ş: 's', ü: 'u', Ü: 'u',
};

/** ASCII-folds a display name into an email local part (Ayşe Şahin → ayse.sahin). */
function slug(value: string): string {
    return value
        .split('')
        .map((ch) => TR_MAP[ch] ?? ch)
        .join('')
        .toLowerCase()
        .normalize('NFD')
        .replace(/[̀-ͯ]/g, '')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');
}

const DAY = 86_400_000;

/** ISO timestamp `days` ago, anchored to the moment the dataset is built. */
function daysAgo(days: number, hourOffset = 0): string {
    return new Date(Date.now() - days * DAY - hourOffset * 3_600_000).toISOString();
}

function pad(n: number, width = 2): string {
    return String(n).padStart(width, '0');
}

function buildUsers(p: DemoProfile): AdminUser[] {
    const users: AdminUser[] = [];
    const seen = new Set<string>();

    for (let i = 0; i < USER_COUNT; i++) {
        const given = p.givenNames[i % p.givenNames.length];
        const cycle = Math.floor(i / p.givenNames.length);
        const family = p.familyNames[(i + cycle * 7) % p.familyNames.length];

        let localPart = `${slug(given)}.${slug(family)}`;
        if (seen.has(localPart)) localPart = `${localPart}${i}`;
        seen.add(localPart);

        const ouIndex = i % p.orgUnits.length;
        const titleIndex = i % p.titles.length;
        const institution = p.institutions[i % p.institutions.length];

        // Every 9th person is suspended; the first and the sixth are admins.
        const suspended = i % 9 === 8;
        const isAdmin = i === 0 || i === 5;

        const user: AdminUser = {
            id: `1${pad(100000000000000 + i * 7919, 20)}`.slice(0, 21),
            primaryEmail: `${localPart}@${p.domain}`,
            name: {
                fullName: `${given} ${family}`,
                givenName: given,
                familyName: family,
            },
            suspended,
            isAdmin,
            creationTime: daysAgo(400 - i * 5),
            lastLoginTime: suspended ? daysAgo(45 + i) : daysAgo(i % 14, i % 23),
            orgUnitPath: `/${p.orgUnits[ouIndex]}`,
            phones: [{ value: `${p.phonePrefix} ${pad((i % 97) + 1)}`, type: 'mobile' }],
            organizations: [
                {
                    title: p.titles[titleIndex],
                    department: institution.name,
                    primary: true,
                    customType: 'work',
                },
            ],
            aliases: i % 11 === 0 ? [`${slug(given)}@${p.domain}`] : [],
        };
        users.push(user);
    }
    return users;
}

function buildGroups(p: DemoProfile): AdminGroup[] {
    return p.groups.map((g, i) => ({
        id: `0${pad(200000000000000 + i * 104729, 19)}`.slice(0, 20),
        email: `${g.localPart}@${p.domain}`,
        name: g.name,
        description: g.description,
    }));
}

const ROLES: Array<GroupMember['role']> = ['OWNER', 'MANAGER', 'MEMBER'];
const DELIVERY: Array<GroupMember['deliverySettings']> = ['ALL_MAIL', 'DAILY', 'DIGEST', 'NONE'];

function buildMembership(p: DemoProfile, users: AdminUser[], groups: AdminGroup[]) {
    const groupMembers: Record<string, GroupMember[]> = {};
    const userGroups: Record<string, string[]> = {};

    for (const u of users) userGroups[u.primaryEmail] = [];

    groups.forEach((group, gi) => {
        const members: GroupMember[] = [];

        users.forEach((u, ui) => {
            // "All staff" gets everyone; the department groups get their own org
            // unit; the rest get a deterministic slice so member counts vary.
            const orgUnitName = (u.orgUnitPath ?? '').replace('/', '');
            const isDepartmentGroup = gi >= 1 && gi <= 5;
            const departmentIndex = gi; // groups[1..5] mirror orgUnits[3,1,2,4,5]
            const orgUnitMatch = p.orgUnits[[0, 3, 1, 2, 4, 5][departmentIndex] ?? 0] === orgUnitName;

            let include: boolean;
            if (gi === 6) include = !u.suspended;                 // all staff
            else if (gi === 0) include = u.isAdmin || ui % 17 === 0; // leadership
            else if (isDepartmentGroup) include = orgUnitMatch;
            else include = (ui + gi) % 9 === 0;                    // announcements / atlas / support

            if (!include) return;

            members.push({
                id: `${group.id.slice(0, 8)}${pad(ui, 6)}`,
                email: u.primaryEmail,
                role: members.length === 0 ? 'OWNER' : ROLES[(ui + gi) % 3],
                type: 'USER',
                status: 'ACTIVE',
                deliverySettings: DELIVERY[(ui + gi) % DELIVERY.length],
            });
            userGroups[u.primaryEmail].push(group.email);
        });

        groupMembers[group.email] = members;
    });

    return { groupMembers, userGroups };
}

function buildGroupSettings(groups: AdminGroup[]): Record<string, GroupSettings> {
    const settings: Record<string, GroupSettings> = {};
    groups.forEach((g, i) => {
        const readOnly = i === 7; // the announcements group is locked down
        settings[g.email] = {
            whoCanJoin: readOnly ? 'INVITED_CAN_JOIN' : 'ALL_IN_DOMAIN_CAN_JOIN',
            whoCanPostMessage: readOnly ? 'ALL_MANAGERS_CAN_POST' : 'ALL_MEMBERS_CAN_POST',
            whoCanViewGroup: 'ALL_IN_DOMAIN_CAN_VIEW',
            whoCanViewMembership: 'ALL_MEMBERS_CAN_VIEW',
            whoCanContactOwner: 'ALL_IN_DOMAIN_CAN_CONTACT',
            allowExternalMembers: i === 9 ? 'true' : 'false',
            allowWebPosting: 'true',
            isArchived: 'true',
            archiveOnly: 'false',
            messageModerationLevel: readOnly ? 'MODERATE_NON_MEMBERS' : 'MODERATE_NONE',
            primaryLanguage: 'en-US',
        };
    });
    return settings;
}

function buildGroupAliases(p: DemoProfile, groups: AdminGroup[]): Record<string, GroupAlias[]> {
    const aliases: Record<string, GroupAlias[]> = {};
    groups.forEach((g, i) => {
        aliases[g.email] = i % 3 === 0
            ? [{ alias: `${g.email.split('@')[0]}@${p.secondaryDomain}`, primaryEmail: g.email }]
            : [];
    });
    return aliases;
}

function buildTemplates(p: DemoProfile): DemoTemplate[] {
    const L = p.signatureLabels;

    const standard = `
<table cellpadding="0" cellspacing="0" style="font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#1e293b;">
  <tr>
    <td style="padding-right:18px;border-right:2px solid #6366f1;vertical-align:middle;">
      <img src="{{image_1}}" alt="${p.companyName}" width="180" />
    </td>
    <td style="padding-left:18px;vertical-align:middle;">
      <div style="font-size:15px;font-weight:700;color:#0f172a;">{{ad_soyad}}</div>
      <div style="color:#475569;padding-bottom:6px;">{{unvan}} &middot; {{kurum_adi}}</div>
      <div><a href="mailto:{{eposta}}" style="color:#6366f1;text-decoration:none;">{{eposta}}</a></div>
      <div style="color:#475569;">${L.mobile}: {{telefon}} &middot; ${L.office}: {{kurum_telefon}}</div>
      <div style="color:#94a3b8;font-size:12px;padding-top:4px;">{{kurum_adres}}</div>
    </td>
  </tr>
</table>`.trim();

    const executive = `
<table cellpadding="0" cellspacing="0" style="font-family:Georgia,'Times New Roman',serif;font-size:13px;color:#1e293b;">
  <tr><td><img src="{{image_1}}" alt="${p.companyName}" width="200" /></td></tr>
  <tr><td style="padding-top:10px;"><img src="{{image_3}}" alt="" width="320" height="3" /></td></tr>
  <tr>
    <td style="padding-top:10px;">
      <div style="font-size:16px;font-weight:700;letter-spacing:0.3px;color:#0f172a;">{{ad_soyad}}</div>
      <div style="color:#64748b;font-style:italic;padding-bottom:8px;">{{unvan}}</div>
      <div style="color:#475569;">{{kurum_adi}} &middot; {{kurum_telefon}}</div>
      <div><a href="mailto:{{eposta}}" style="color:#6366f1;text-decoration:none;">{{eposta}}</a></div>
    </td>
  </tr>
</table>`.trim();

    const sales = `
<table cellpadding="0" cellspacing="0" style="font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#1e293b;">
  <tr>
    <td>
      <div style="font-size:15px;font-weight:700;color:#0f172a;">{{ad_soyad}}</div>
      <div style="color:#475569;padding-bottom:6px;">{{unvan}} &middot; {{kurum_adi}}</div>
      <div style="color:#475569;">${L.mobile}: {{telefon}}</div>
      <div><a href="mailto:{{eposta}}" style="color:#6366f1;text-decoration:none;">{{eposta}}</a></div>
      <div style="padding-top:8px;">
        <a href="https://example.com" style="text-decoration:none;"><img src="{{image_2}}" alt="LinkedIn" width="24" height="24" /></a>
      </div>
    </td>
  </tr>
</table>`.trim();

    const minimal = `
<div style="font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#1e293b;">
  <strong>{{ad_soyad}}</strong> &mdash; {{unvan}}<br />
  {{kurum_adi}} &middot; <a href="mailto:{{eposta}}" style="color:#6366f1;text-decoration:none;">{{eposta}}</a>
</div>`.trim();

    const bodies = [standard, executive, sales, minimal];

    return p.templateNames.map((name, i) => ({
        id: i + 1,
        name,
        htmlContent: bodies[i],
        isDefault: i === 0,
        createdBy: `${p.adminLocalPart}@${p.domain}`,
        updatedBy: `${p.adminLocalPart}@${p.domain}`,
        createdAt: daysAgo(120 - i * 20),
        updatedAt: daysAgo(9 - i * 2),
    }));
}

// Media rows are per-template ({{image_1}} means "the first image of THIS
// template"), so every template that references an image token needs its own
// row — otherwise the preview renders a broken <img>.
function buildMedia(p: DemoProfile): DemoMedia[] {
    const urls = [
        signatureWordmarkDataUri(p.companyName),
        socialBadgeDataUri,
        dividerDataUri,
    ];

    const rows: DemoMedia[] = [];
    let id = 1;

    // Templates 1–3 use images; the minimal template (4) is text-only.
    for (const templateId of [1, 2, 3]) {
        p.mediaNames.forEach((name, i) => {
            rows.push({
                id: id++,
                name,
                driveFileId: `demo-drive-file-${templateId}-${i + 1}`,
                publicUrl: urls[i],
                mimeType: 'image/svg+xml',
                templateId,
                createdBy: `${p.adminLocalPart}@${p.domain}`,
                token: `image_${i + 1}`,
                createdAt: daysAgo(100 - i * 10),
            });
        });
    }
    return rows;
}

function buildJobs(p: DemoProfile, users: AdminUser[]): ServerJob[] {
    const admin = `${p.adminLocalPart}@${p.domain}`;
    const emailsAt = (start: number, count: number) =>
        users.slice(start, start + count).map((u) => u.primaryEmail);

    const completed = (
        id: string,
        type: ServerJob['type'],
        total: number,
        failed: number,
        ageDays: number,
        start: number,
    ): ServerJob => {
        const emails = emailsAt(start, total);
        const failedEmails = emails.slice(0, failed);
        const okEmails = emails.slice(failed);
        return {
            id,
            type,
            status: failed > 0 && failed === total ? 'FAILED' : 'COMPLETED',
            payload: { rows: emails.map((email) => ({ email })) },
            result: {
                errors: failedEmails.map((email, i) => ({ email, error: p.jobErrors[i % p.jobErrors.length] })),
                succeededEmails: okEmails,
            },
            executionReport: {
                totalProcessed: total,
                successCount: total - failed,
                failedCount: failed,
                succeededItems: okEmails.map((email, i) => ({ email, rowNumber: failed + i + 1 })),
                failedItems: failedEmails.map((email, i) => ({
                    email,
                    rowNumber: i + 1,
                    step: type === 'BULK_SIGNATURE_PUSH' ? 'gmail.settings.sendAs.patch' : 'directory.users.update',
                    error: p.jobErrors[i % p.jobErrors.length],
                })),
                executedAt: daysAgo(ageDays),
            },
            progress: total,
            total,
            succeeded: total - failed,
            failed,
            createdBy: admin,
            createdAt: daysAgo(ageDays, 1),
            startedAt: daysAgo(ageDays, 1),
            completedAt: daysAgo(ageDays),
            cancelledAt: null,
        };
    };

    const jobs: ServerJob[] = [
        completed('job-2041', 'BULK_SIGNATURE_PUSH', 48, 2, 1, 0),
        completed('job-2040', 'BULK_SUSPEND', 6, 0, 2, 8),
        completed('job-2039', 'BULK_SIGNATURE_PUSH', 32, 0, 4, 12),
        completed('job-2038', 'SIGNATURE_AUDIT', 64, 0, 5, 0),
        completed('job-2037', 'BULK_GROUP_ADD', 14, 1, 7, 20),
        completed('job-2036', 'BULK_DELETE', 3, 3, 9, 30),
        completed('job-2035', 'BULK_SIGNATURE_PUSH', 21, 4, 12, 5),
        completed('job-2034', 'BULK_SUSPEND', 9, 0, 15, 24),
        completed('job-2033', 'SIGNATURE_AUDIT', 60, 0, 18, 0),
        completed('job-2032', 'BULK_SIGNATURE_PUSH', 40, 1, 22, 10),
        completed('job-2031', 'BULK_GROUP_ADD', 7, 0, 26, 16),
    ];

    // One cancelled job — the history filter chips need something to select.
    const cancelledEmails = emailsAt(36, 18);
    jobs.push({
        id: 'job-2030',
        type: 'BULK_SIGNATURE_PUSH',
        status: 'CANCELLED',
        payload: { rows: cancelledEmails.map((email) => ({ email })) },
        result: { errors: [], succeededEmails: cancelledEmails.slice(0, 7) },
        executionReport: null,
        progress: 7,
        total: 18,
        succeeded: 7,
        failed: 0,
        createdBy: admin,
        createdAt: daysAgo(30, 2),
        startedAt: daysAgo(30, 2),
        completedAt: null,
        cancelledAt: daysAgo(30),
    });

    // A live job so the dashboard's "active jobs" card has something to show.
    const runningEmails = emailsAt(0, 52);
    jobs.unshift({
        id: 'job-2042',
        type: 'BULK_SIGNATURE_PUSH',
        status: 'RUNNING',
        payload: { rows: runningEmails.map((email) => ({ email })) },
        result: null,
        executionReport: null,
        progress: 34,
        total: 52,
        succeeded: 33,
        failed: 1,
        createdBy: admin,
        createdAt: daysAgo(0, 1),
        startedAt: daysAgo(0, 1),
        completedAt: null,
        cancelledAt: null,
    });

    return jobs;
}

function buildLoginActivities(users: AdminUser[]): any[] {
    return users.slice(0, 20).map((u, i) => ({
        id: {
            time: daysAgo(Math.floor(i / 3), (i % 3) * 5),
            uniqueQualifier: `${1000 + i}`,
            applicationName: 'login',
            customerId: 'C00demo01',
        },
        actor: { email: u.primaryEmail, profileId: u.id },
        ipAddress: `203.0.113.${(i * 7) % 250 + 1}`,
        events: [{ type: 'login', name: i % 8 === 7 ? 'login_failure' : 'login_success' }],
    }));
}

function buildSignatures(users: AdminUser[], templates: DemoTemplate[], media: DemoMedia[]): Record<string, string> {
    const signatures: Record<string, string> = {};
    const wordmark = media.find((m) => m.token === 'image_1')?.publicUrl ?? '';

    users.forEach((u, i) => {
        // Roughly a fifth of the directory has no signature yet — that is what
        // the audit screen is meant to surface.
        if (i % 5 === 4) return;
        const template = templates[0];
        signatures[u.primaryEmail] = template.htmlContent
            .replace(/\{\{\s*ad_soyad[^}]*\}\}/g, u.name.fullName)
            .replace(/\{\{\s*unvan[^}]*\}\}/g, u.organizations?.[0]?.title ?? '')
            .replace(/\{\{\s*kurum_adi[^}]*\}\}/g, u.organizations?.[0]?.department ?? '')
            .replace(/\{\{\s*eposta[^}]*\}\}/g, u.primaryEmail)
            .replace(/\{\{\s*telefon[^}]*\}\}/g, u.phones?.[0]?.value ?? '')
            .replace(/\{\{\s*image_1[^}]*\}\}/g, wordmark)
            .replace(/\{\{[^}]+\}\}/g, '');
    });
    return signatures;
}

export function buildDataset(profile: DemoProfile): DemoDataset {
    const p = profile;
    const adminEmail = `${p.adminLocalPart}@${p.domain}`;

    const users = buildUsers(p);
    const groups = buildGroups(p);
    const { groupMembers, userGroups } = buildMembership(p, users, groups);
    const templates = buildTemplates(p);
    const media = buildMedia(p);

    const orgUnits: OrgUnit[] = p.orgUnits.map((name, i) => ({
        orgUnitId: `id:ou${pad(i + 1, 3)}`,
        name,
        orgUnitPath: `/${name}`,
        parentOrgUnitPath: '/',
        description: '',
    }));

    const domains: Domain[] = [
        { domainName: p.domain, isPrimary: true, verified: true },
        { domainName: p.secondaryDomain, isPrimary: false, verified: true },
    ];

    const config: AppConfigDTO = {
        companyName: p.companyName,
        sidebarAbbr: p.sidebarAbbr,
        logoPath: 'demo://logo.svg',
        emailSenderName: p.emailSenderName,
        allowedDomain: p.domain,
        language: p.lang,
        onboardingStep: null,
        onboardingCompletedAt: daysAgo(180),
        googleClientId: '1234567890-demoprototypeclientid.apps.googleusercontent.com',
        termsAcceptedAt: daysAgo(180),
        // Must equal CURRENT_TERMS_VERSION (src/lib/legal.ts) or the acceptance
        // modal covers every screen.
        termsVersion: '1',
        // '0' disables the idle timer — a vault lock screen must never appear
        // mid-screenshot.
        autoLockMinutes: '0',
    };

    return {
        profile: p,
        config,
        authUser: {
            email: adminEmail,
            name: `${p.adminGivenName} ${p.adminFamilyName}`,
            picture: avatarDataUri(`${p.adminGivenName[0]}${p.adminFamilyName[0]}`),
        },
        logoDataUrl: logoDataUri(p.sidebarAbbr),
        users,
        orgUnits,
        domains,
        groups,
        groupMembers,
        groupAliases: buildGroupAliases(p, groups),
        groupSettings: buildGroupSettings(groups),
        userGroups,
        titles: p.titles.map((name, i) => ({
            id: i + 1,
            name,
            createdBy: adminEmail,
            updatedBy: adminEmail,
            createdAt: daysAgo(170 - i),
            updatedAt: daysAgo(170 - i),
        })),
        institutions: p.institutions.map((inst, i) => ({
            id: i + 1,
            name: inst.name,
            address: inst.address,
            phone: inst.phone,
            createdBy: adminEmail,
            updatedBy: adminEmail,
            createdAt: daysAgo(175 - i),
            updatedAt: daysAgo(60 - i),
        })),
        templates,
        media,
        jobs: buildJobs(p, users),
        loginActivities: buildLoginActivities(users),
        storage: { usedStorageMb: 831_488, totalStorageMb: 2_097_152 },
        serviceAccount: {
            configured: true,
            email: `goworks-signature@demo-prototype.iam.gserviceaccount.com`,
            clientId: '109876543210987654321',
        },
        dwdScopes: [
            'https://www.googleapis.com/auth/admin.directory.user',
            'https://www.googleapis.com/auth/admin.directory.group',
            'https://www.googleapis.com/auth/admin.reports.audit.readonly',
            'https://www.googleapis.com/auth/apps.groups.settings',
            'https://www.googleapis.com/auth/gmail.settings.basic',
            'https://www.googleapis.com/auth/gmail.settings.sharing',
            'https://www.googleapis.com/auth/drive.file',
        ],
        oauth: {
            clientId: '1234567890-demoprototypeclientid.apps.googleusercontent.com',
            hasSecret: true,
        },
        signatures: buildSignatures(users, templates, media),
    };
}
